# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-17 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('id_name', models.IntegerField(default='0')),
                ('edad', models.IntegerField(default='0')),
                ('genero', models.CharField(default='empty', max_length=30)),
                ('birthday', models.DateField()),
                ('smoker', models.BooleanField()),
                ('year_diag', models.IntegerField(default='1')),
                ('other_disorder', models.CharField(default='empty', max_length=250)),
                ('educational_level', models.IntegerField(default='0')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('height', models.IntegerField(default='0')),
                ('session_conunt', models.IntegerField(default='0')),
            ],
        ),
    ]
