# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkinson_mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='birthday',
            field=models.CharField(max_length=30),
        ),
    ]
