# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-18 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkinson_mobile', '0003_auto_20190817_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='weight',
            field=models.CharField(max_length=30),
        ),
    ]
