# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkinson_mobile', '0004_auto_20190818_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
