# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-18 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkinson_mobile', '0006_auto_20190818_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='birthday',
            field=models.DateField(),
        ),
    ]
