# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-08-18 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apkinson_mobile', '0007_auto_20190818_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='session_conunt',
            new_name='session_count',
        ),
    ]
